const patientroute = require('../controllers/patient')
const express = require('express')
const router = express.Router()


router.post('/signup',patientroute.registerPatient)
router.post('/signin',patientroute.loginPatient)
router.put('/onboard1update',patientroute.onBoard1Patientupdate)
router.post('/onboard2add',patientroute.onBoard2Patientadd)
router.post('/addmedications/:Email_id',patientroute.addmedications)
router.get('/getAllPatients',patientroute.getAllPatients)
router.post('/addHeartRateInfo/:Email_id',patientroute.addHeartRateInfo)
router.post('/addBloodPressureInfo/:Email_id',patientroute.addBloodPressureInfo)
router.post('/adddOxygenInfo/:Email_id',patientroute.adddOxygenInfo)
router.post('/addrespiratoryInfo/:Email_id',patientroute.addrespiratoryInfo)
router.post('/addTemperatureInfo/:Email_id',patientroute.addTemperatureInfo)
router.post('/addHaemoglobinInfo/:Email_id',patientroute.addHaemoglobinInfo)
router.post('/addGlucoseInfo/:Email_id',patientroute.addGlucoseInfo)
router.post('/addThyroidInfo/:Email_id',patientroute.addThyroidInfo)
router.post('/addFitbitinfo/:Email_id',patientroute.addFitbitinfo)
router.post('/addGlucometerinfo/:Email_id',patientroute.addGlucometerinfo)
module.exports = router